#Requires -Version 5.1

<#
.SYNOPSIS
    Phase 6 Configuration Update Script for Windows (Simplified)

.DESCRIPTION
    Orchestrates the Phase 6 configuration update process with proper prerequisite validation and error handling.
    Reads Phase 5 sensitivity analysis results and automatically updates Phase 6 YAML configuration to refine
    only the 4 most sensitive parameters while fixing the remaining 7 parameters.

.PARAMETER SensitivityJson
    Path to Phase 5 sensitivity analysis JSON file (default: optimization/results/phase5_sensitivity_analysis.json)

.PARAMETER Phase6Yaml
    Path to Phase 6 YAML configuration file (default: optimization/configs/phase6_refinement.yaml)

.PARAMETER OutputYaml
    Path to output YAML file (default: same as Phase6Yaml)

.PARAMETER DryRun
    Show what would be changed without writing files

.PARAMETER Verbose
    Enable verbose logging

.EXAMPLE
    .\optimization\scripts\run_phase6_config_update_simple.ps1

.EXAMPLE
    .\optimization\scripts\run_phase6_config_update_simple.ps1 -DryRun -Verbose

.NOTES
    Prerequisites:
    - Phase 5 must complete successfully
    - Phase 5 sensitivity analysis must be run
    - sensitivity_analysis.json must contain real data (not placeholders)
    
    Expected outputs:
    - Updated phase6_refinement.yaml with 4 parameters for refinement
    - Console summary showing before/after comparison
    - Validation confirmation that config is compatible with grid_search.py
    
    Estimated runtime: < 1 minute
#>

param(
    [string]$SensitivityJson = "optimization/results/phase5_sensitivity_analysis.json",
    [string]$Phase6Yaml = "optimization/configs/phase6_refinement.yaml",
    [string]$OutputYaml = "",
    [switch]$DryRun,
    [switch]$Verbose
)

# Color definitions for output formatting
$ColorGreen = "Green"
$ColorRed = "Red"
$ColorYellow = "Yellow"
$ColorWhite = "White"

function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = $ColorWhite
    )
    Write-Host $Message -ForegroundColor $Color
}

function Test-Prerequisites {
    Write-ColorOutput "Testing prerequisites..." $ColorYellow
    
    # Check that sensitivity analysis JSON exists
    if (-not (Test-Path $SensitivityJson)) {
        Write-ColorOutput "ERROR: Sensitivity analysis JSON not found at $SensitivityJson" $ColorRed
        Write-ColorOutput "Please run Phase 5 sensitivity analysis first:" $ColorRed
        Write-ColorOutput "  .\optimization\scripts\run_phase5_sensitivity_analysis.ps1" $ColorRed
        exit 2
    }
    Write-ColorOutput "✓ Sensitivity analysis JSON found" $ColorGreen
    
    # Read JSON and verify it contains real data (not placeholder values)
    try {
        $sensitivityData = Get-Content $SensitivityJson | ConvertFrom-Json
        
        # Check for placeholder values
        $hasPlaceholders = $false
        $jsonString = Get-Content $SensitivityJson -Raw
        
        if ($jsonString -match '\[Generated by script\]') {
            $hasPlaceholders = $true
        }
        
        if ($hasPlaceholders) {
            Write-ColorOutput "ERROR: Sensitivity analysis contains placeholder data" $ColorRed
            Write-ColorOutput "Please run Phase 5 sensitivity analysis first:" $ColorRed
            Write-ColorOutput "  .\optimization\scripts\run_phase5_sensitivity_analysis.ps1" $ColorRed
            exit 2
        }
        
        # Check that top_4_sensitive_parameters has exactly 4 entries
        if (-not $sensitivityData.phase6_configuration_suggestion.parameters_to_refine) {
            Write-ColorOutput "ERROR: Sensitivity analysis missing parameters_to_refine" $ColorRed
            Write-ColorOutput "Please run Phase 5 sensitivity analysis first:" $ColorRed
            Write-ColorOutput "  .\optimization\scripts\run_phase5_sensitivity_analysis.ps1" $ColorRed
            exit 2
        }
        
        $refineCount = $sensitivityData.phase6_configuration_suggestion.parameters_to_refine.Count
        if ($refineCount -ne 4) {
            Write-ColorOutput "ERROR: Expected 4 parameters to refine, found $refineCount" $ColorRed
            Write-ColorOutput "Please run Phase 5 sensitivity analysis first:" $ColorRed
            Write-ColorOutput "  .\optimization\scripts\run_phase5_sensitivity_analysis.ps1" $ColorRed
            exit 2
        }
        
        Write-ColorOutput "✓ Sensitivity analysis contains real data with 4 parameters to refine" $ColorGreen
        
    } catch {
        Write-ColorOutput "ERROR: Failed to parse sensitivity analysis JSON: $($_.Exception.Message)" $ColorRed
        Write-ColorOutput "Please run Phase 5 sensitivity analysis first:" $ColorRed
        Write-ColorOutput "  .\optimization\scripts\run_phase5_sensitivity_analysis.ps1" $ColorRed
        exit 2
    }
}

function Backup-ExistingConfig {
    if ($DryRun) {
        Write-ColorOutput "DRY RUN: Would create backup of existing configuration" $ColorYellow
        return
    }
    
    Write-ColorOutput "Creating backup of existing configuration..." $ColorYellow
    
    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $backupPath = "$Phase6Yaml.backup.$timestamp"
    
    try {
        Copy-Item $Phase6Yaml $backupPath -Force
        Write-ColorOutput "✓ Backup created: $backupPath" $ColorGreen
    } catch {
        Write-ColorOutput "WARNING: Failed to create backup: $($_.Exception.Message)" $ColorYellow
        Write-ColorOutput "Continuing without backup..." $ColorYellow
    }
}

function Invoke-ConfigUpdate {
    Write-ColorOutput "Executing Phase 6 configuration update..." $ColorYellow
    
    # Build command
    $pythonScript = "optimization/tools/update_phase6_config.py"
    $command = "python `"$pythonScript`" --sensitivity-json `"$SensitivityJson`" --phase6-yaml `"$Phase6Yaml`""
    
    if ($OutputYaml) {
        $command += " --output-yaml `"$OutputYaml`""
    }
    
    if ($DryRun) {
        $command += " --dry-run"
    }
    
    if ($Verbose) {
        $command += " --verbose"
    }
    
    Write-ColorOutput "Command: $command" $ColorWhite
    
    try {
        # Execute command and capture output
        $result = Invoke-Expression $command 2>&1
        $exitCode = $LASTEXITCODE
        
        # Display output
        Write-Host $result
        
        if ($exitCode -ne 0) {
            Write-ColorOutput "ERROR: Python script failed with exit code $exitCode" $ColorRed
            Write-ColorOutput "Check the output above for error details." $ColorRed
            exit 3
        }
        
        Write-ColorOutput "✓ Configuration update completed successfully" $ColorGreen
        
    } catch {
        Write-ColorOutput "ERROR: Failed to execute Python script: $($_.Exception.Message)" $ColorRed
        exit 3
    }
}

function Show-NextSteps {
    Write-ColorOutput "`nNext Steps:" $ColorGreen
    Write-ColorOutput "===========" $ColorGreen
    
    Write-ColorOutput "1. Review updated configuration:" $ColorWhite
    Write-ColorOutput "   Get-Content optimization/configs/phase6_refinement.yaml | Select-String 'parameters:' -A 20" $ColorYellow
    
    Write-ColorOutput "`n2. Run Phase 6 optimization:" $ColorWhite
    Write-ColorOutput "   .\optimization\scripts\run_phase6.ps1" $ColorYellow
    
    Write-ColorOutput "`n3. Expected runtime: 4-6 hours with 8 workers" $ColorWhite
    Write-ColorOutput "   (down from 20-40 hours with original configuration)" $ColorWhite
    
    Write-ColorOutput "`n4. Monitor progress and results:" $ColorWhite
    Write-ColorOutput "   - Check optimization/results/phase6_refinement_results.csv" $ColorWhite
    Write-ColorOutput "   - Review optimization/results/phase6_refinement_results_top_10.json" $ColorWhite
    Write-ColorOutput "   - Analyze optimization/results/phase6_refinement_results_pareto_frontier.json" $ColorWhite
}

# Main execution
try {
    Write-ColorOutput "Phase 6 Configuration Update Script" $ColorGreen
    Write-ColorOutput "====================================" $ColorGreen
    Write-ColorOutput ""
    Write-ColorOutput "Parameters:" $ColorWhite
    Write-ColorOutput "  Sensitivity JSON: $SensitivityJson" $ColorWhite
    Write-ColorOutput "  Phase 6 YAML: $Phase6Yaml" $ColorWhite
    Write-ColorOutput "  Output YAML: $(if ($OutputYaml) { $OutputYaml } else { 'Same as Phase 6 YAML' })" $ColorWhite
    Write-ColorOutput "  Dry Run: $DryRun" $ColorWhite
    Write-ColorOutput "  Verbose: $Verbose" $ColorWhite
    Write-ColorOutput ""
    
    # Execute workflow
    Test-Prerequisites
    Backup-ExistingConfig
    Invoke-ConfigUpdate
    Show-NextSteps
    
    Write-ColorOutput "`nPhase 6 configuration update completed successfully!" $ColorGreen
    
} catch {
    Write-ColorOutput "`nERROR: Phase 6 configuration update failed: $($_.Exception.Message)" $ColorRed
    exit 1
}
